version: '3'

services:

  app:
    build: .
    image: tiny-cuda-nn-python:latest
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes:
       - ./results:/app/results